config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :tags

  root to: 'visitors#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	mount_uploader :image, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:location, :note, :url, :audio, :video, :image, :phone)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
		
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Tags',  tags_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Safe Haven" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Safe Haven" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/tags/_audio.html.erb
<!-- <p>
  <audio controls><source src="<%#= @tag.audio %>" type="audio/mpeg"></audio>
</p> -->

  <p>
    <strong>Audio:</strong><br>
    <audio controls><source src="<%= @tag.audio %>" type="audio/mpeg"></audio>
  </p>

app/views/tags/_form.html.erb
<div class="large-8 medium-centered columns ">
    <div class="site forms">
      

    <%= form_for(@tag) do |f| %>
      <% if @tag.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

          <ul>
          <% @tag.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :audio %><br>
    <%= f.text_field :audio %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit class: "button small radius right success" %>
  </div>
<% end %>

app/views/tags/_image.html.erb
<!-- <p>
  <img src="<%= @tag.image %>">
</p> -->


  <p>
    <strong>Image:</strong>
    <img src="<%= @tag.image %>">
  </p>

app/views/tags/_note.html.erb
<p class="note">
  <%= @tag.note %>
</p>

app/views/tags/_phone.html.erb
<meta http-equiv="refresh" content="0; url=tel:<%= @tag.phone %>" />

app/views/tags/_url.html.erb
<meta http-equiv="refresh" content="0; url=<%= @tag.url %>" />

app/views/tags/_video.html.erb
<!-- 
<p class='hidden_sm'>
  <iframe width="560" height="315" src="//www.youtube.com/embed/<%= @tag.video %>"frameborder="0" allowfullscreen></iframe>
</p>


<p class='visible_sm'>
  <iframe width="400" height="215" src="//www.youtube.com/embed/<%= @tag.video %>"frameborder="0" allowfullscreen></iframe>
</p> -->

<div id="ytplayer"></div>

<script>
  // Load the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // Replace the 'ytplayer' element with an <iframe> and
  // YouTube player after the API code downloads.
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('ytplayer', {
      height: (Math.floor($(window).width()*0.43875)),
      width: (Math.floor($(window).width()*0.78)),
      videoId: '<%= @tag.video %>'
    });
  }
</script>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="margin-10"></div>
<div class="row">

  <div class="medium-10 medium-offset-1 columns">
<div class="padding-10"></div>
<div class="padding-10"></div>

<div class="row">
<div class="medium-12 columns">
    <h1>Listing tags</h1>

        <table>
          <thead>
            <tr>
              <th>Location</th>
              <!-- <th>Note</th> -->
              <!-- <th>Url</th> -->
              <!-- <th>Audio</th> -->
              <!-- <th>Video</th> -->
              <!-- <th>Image</th> -->
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @tags.each do |tag| %>
              <tr>
                <td><%= tag.location %></td>
                <!-- <td><%= tag.note %></td> -->
                <!-- <td><%= tag.url %></td> -->
                <!-- <td><%= tag.audio %></td> -->
                <!-- <td><%= tag.video %></td> -->
                <!-- <td><%= tag.image %></td> -->
                <td><%= link_to 'Show', tag %></td>
                <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
                <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>


    </div> 
</div>

app/views/tags/new.html.erb
<div class="margin-10"></div>
<div class="row">

	<div class="medium-6 medium-offset-3 columns">


		<h1>New tag</h1>

		<%= render 'form' %>

		<%= link_to 'Back', tags_path %>

	</div>
</div>

app/views/tags/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Bentham' rel='stylesheet' type='text/css'>
<script type="text/javascript">
  $('body').css('background','#14110E');
  $('.note').css('color','#EBE6E2');
  </script>

<p id="notice"><%= notice %></p>

<div class="margin-10"></div>
<div class="row">


  

<!--   <p>
    <strong>Location:</strong>
    <%#= @tag.location %>
  </p>

  <p>
    <strong>Note:</strong>
    <%#= @tag.note %>
  </p> -->


 <!--  <p>
    <strong>Url:</strong>
    # <a href ="<%#= @tag.url %>"><%#= @tag.url %></a>
  </p> -->

  <% if @tag.note != "" %> 
    <div class="medium-10 medium-offset-1 columns tag">
    <%= render 'note' %>
    </div>
  <% end %>


  <% if @tag.url != "" %>
    <div class="medium-10 medium-offset-1 columns tag">
    <%= render 'url' %> 
    </div>
  <% end %>


  <% unless @tag.image %> 
    <div class="medium-10 medium-offset-1 columns tag">
    <%= render 'image' %>
    </div>
  <% end %>


  <% if @tag.audio != "" %>
    <div class="medium-10 medium-offset-1 columns tag">
    <%= render 'audio'%> 
    </div>
  <% end %>


  <% if @tag.video != "" %> 
    <div class="medium-10 medium-offset-1 columns tag">
    <%= render 'video' %>
    </div>
  <% end %>


  <% if @tag.phone != "" %> 
    <div class="medium-10 medium-offset-1 columns tag">
    <%= render 'phone' %>
    </div>
  <% end %>


  <%= link_to 'Edit', edit_tag_path(@tag) %> |
  <%= link_to 'Back', tags_path %>

</div>
</div>

<script type="text/javascript">

  
  $(".note").css("font-size", (Math.floor($(window).width()/12)+'px'));
  // $(window).addEventListener("resize", function(){
  //   $(".note").css("font-size", (Math.floor($(window).width()/48)+'px'));});
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="row">
<div class="medium-12 columns">

<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'button success small radius right' %>

  </div> 
</div>

app/views/users/new.html.erb
  <div class="row">
    <div class="large-7 large-centered columns">
      <div class="form-containers">

    	<div class="form-header-container">
        <div class="large-12 columns  form-header">
          <h1 class="text-center">New user</h1>
        </div>
      </div>

        <%= render 'form' %>

      </div>
    </div>

  </div>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/visitors/index.html.erb
<div id="header">



	


<!--<ul id="ticker01">
    <li>Text 1</li>
	</ul>
 -->


 <div class="large-6 large-offset-3 small-12 small-offset-0 columns content">
<h1>SafeHaven</h1>
<div id="demo1" class="row">

	<div class="item large-12 columns">
		<div class="panel">
			<div class="animated">
				<div><%= image_tag("brain.png", size: "350x279", alt: "Brain")%></div>
				<h2>Your Life</h2>
			</div>
		</div>
	</div>

	<div class="item large-12 columns">
		<div class="panel">
			<div class="animated">
				<div><%= image_tag("brain-blue.png", size: "350x279", alt: "Brain")%></div>
				<h2>Your Home</h2>
			</div>
		</div>
	</div>

	<div class="item large-12 columns">
		<div class="panel">
			<div class="animated">
				<div><%= image_tag("brain-orange.png", size: "350x279", alt: "Brain")%></div>
				<h2>Our Help</h2>
			</div>
		</div>
	</div>

	<div class="item large-12 columns">
		<div class="panel">
			<div class="animated">
				<div><%= image_tag("brain-purple.png", size: "350x279", alt: "Brain")%></div>
				<h2>Peace of Mind</h2>
			</div>
		</div>
	</div>

	<div class="item large-12 columns">
		<div class="panel">
			<div class="animated">
				<div><%= image_tag("brain-white.png", size: "350x279", alt: "Brain")%></div>
				<h2>Lorem 5</h2>
			</div>
		</div>
	</div>

</div>

</div>